spring:
    application:
        name: simple-blog

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/simple-blog?serverTimezone=Asia/Seoul
        username: root
        password: chaBest1029!
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        open-in-view: false
        properties:
            hibernate:
                default_batch_fetch_size: 100
                format_sql: true

server:
    port: 9090
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true

